# Generated by Codex on 2026-03-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(blank=True, help_text="The groups this user belongs to.", related_name="customuser_set", related_query_name="customuser", to="auth.group", verbose_name="groups"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="customuser_set", related_query_name="customuser", to="auth.permission", verbose_name="user permissions"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(choices=[("admin", "admin"), ("driver", "driver"), ("farmer", "farmer")], max_length=20),
        ),
    ]
