# Generated by Codex on 2026-03-22

from decimal import Decimal

from django.db import migrations, models


def seed_transport_pricing(apps, schema_editor):
    TransportPricing = apps.get_model("transporters", "TransportPricing")
    defaults = {
        "motorbike": Decimal("100.00"),
        "pickup": Decimal("200.00"),
        "van": Decimal("250.00"),
        "truck": Decimal("350.00"),
    }
    for vehicle_type, price_per_km in defaults.items():
        TransportPricing.objects.update_or_create(
            vehicle_type=vehicle_type,
            defaults={"price_per_km": price_per_km},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("transporters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportPricing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vehicle_type", models.CharField(choices=[("motorbike", "Motorbike"), ("pickup", "Pickup"), ("van", "Van"), ("truck", "Truck")], max_length=20, unique=True)),
                ("price_per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Transport pricing",
                "verbose_name_plural": "Transport pricing",
                "ordering": ["vehicle_type"],
            },
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price_per_km",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(seed_transport_pricing, migrations.RunPython.noop),
    ]
