# Generated by Django 6.0.3 on 2026-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporters', '0003_transportpricing_weight_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportpricing',
            name='max_weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportpricing',
            name='min_weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportpricing',
            name='vehicle_type',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('van', 'Van'), ('pickup', 'Pickup'), ('truck', 'Truck')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('van', 'Van'), ('pickup', 'Pickup'), ('truck', 'Truck')], max_length=20),
        ),
    ]
