# Generated by Codex on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporters", "0004_alter_transportpricing_max_weight_kg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportpricing",
            name="vehicle_type",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(max_length=50),
        ),
    ]
