# Generated by Django 6.0.3 on 2026-04-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0002_booking_dropoff_place_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_kes", models.DecimalField(decimal_places=2, max_digits=10)),
                ("phone_number", models.CharField(max_length=20)),
                ("merchant_request_id", models.CharField(blank=True, max_length=100)),
                ("checkout_request_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("mpesa_receipt_number", models.CharField(blank=True, max_length=100)),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                ("result_code", models.IntegerField(blank=True, null=True)),
                ("result_desc", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("stk_push_sent", "STK Push Sent"), ("paid_held", "Paid Held"), ("failed", "Failed"), ("cancelled", "Cancelled"), ("released", "Released")], default="pending", max_length=20)),
                ("raw_callback_payload", models.JSONField(blank=True, null=True)),
                ("held_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payment", to="booking.booking")),
                ("farmer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments_made", to=settings.AUTH_USER_MODEL)),
                ("transporter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments_received", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PaymentStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("stk_push_sent", "STK Push Sent"), ("paid_held", "Paid Held"), ("failed", "Failed"), ("cancelled", "Cancelled"), ("released", "Released")], max_length=20)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="payments.payment")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="TransporterPayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_kes", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(choices=[("pending_release", "Pending Release"), ("released", "Released"), ("failed", "Failed")], default="pending_release", max_length=20)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payout", to="booking.booking")),
                ("payment", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payout", to="payments.payment")),
                ("transporter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payouts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
