# Generated by Django 6.0.3 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_dropoff_place_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("pending", "Pending"), ("paid", "Paid")],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("confirmed", "Confirmed"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("picked_up", "Picked Up"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
