# Generated by Django 6.0.3 on 2026-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_payment_status_and_status_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
