# Generated by Django 6.0.3 on 2026-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookingstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type_required',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('van', 'Van'), ('pickup', 'Pickup'), ('truck', 'Truck')], max_length=20),
        ),
    ]
