# Generated by Codex on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_booking_vehicle_type_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="vehicle_type_required",
            field=models.CharField(max_length=50),
        ),
    ]
